### ISSUE TITLE
Error creating administrator account

### ISSUE THREAD

**Issue by zarevskaya** [seanmorley15/AdventureLog#106]
Hi, 
Without https it was impossible to create an account. So I have proxy the url and linked your application to my domain, but I get this error. An idea?

![Screenshot_20240710_095508](https://github.com/seanmorley15/AdventureLog/assets/60230221/d82ab5d9-71d4-4c71-b90b-46077a5ba77e)

Have a nice day!

**Comment by seanmorley15** [comment]
zarevskaya,

Thank you so much for your interest in AdventureLog! I see 2 possible issues for what you are experiencing. 

1. Assuming that your https domain name is the way you are accessing the app. You can remove the `ORGIN` environmental variable completely as its only necessary for non https environments.
2. I have added some fixes to the backend. Repull the docker images and add the following to the docker compose for `server`. Include both the frontend and backend addresses.
EXAMPLE:
`CSRF_TRUSTED_ORIGINS=https://backend.domain.app,https://frontend.app`
It is highly recommended that if you use the domain for the frontend you also use it for the backend.

If these do not work. Please reach out with logs for both the backend and frontend containers and possibly include the docker compose file so I can debug it.

Hope this helps!

**Comment by zarevskaya** [comment]
Oh, yes, I understand now. Let me try 👍
Thanks for the answer.

**Comment by zarevskaya** [comment]
Yeah! That work fine, I can set up my admin accout.

Either it's a bug or the problem is on the chair but I don't have access to the profile.

/profile

```
SvelteKitError: Not found: /profile

    at resolve2 (file:///app/build/server/index.js:3644:18)

    at resolve (file:///app/build/server/index.js:3477:34)

    at resolve (file:///app/build/server/chunks/hooks.server-26mp9U6D.js:28:16)

    at themeHook (file:///app/build/server/chunks/hooks.server-26mp9U6D.js:119:16)

    at apply_handle (file:///app/build/server/chunks/hooks.server-26mp9U6D.js:10:14)

    at resolve (file:///app/build/server/chunks/hooks.server-26mp9U6D.js:24:35)

    at authHook (file:///app/build/server/chunks/hooks.server-26mp9U6D.js:110:16)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async respond (file:///app/build/server/index.js:3475:22)

    at async Array.ssr (file:///app/build/handler.js:1261:3) {

  status: 404,

  text: 'Not Found'

}
```

**Comment by seanmorley15** [comment]
I'm so glad to hears it working!

Regarding the profile, it was not yet implemented but I have just released a update with a simple profile screen so that it does not cause an error.

Thank you so much for taking the time to use AdventureLog, especially when its in the early stages of development. I have a lot more planned so stay tuned!

**Comment by zarevskaya** [comment]
Ooooooh, ok! 

I was going to tell you about other bugs but knowing that, I'll wait. Thanks a lot for your answers!

**Comment by seanmorley15** [comment]
Thanks, always feel free to add issues!

**Comment by zarevskaya** [comment]
Thank you.
