### ISSUE TITLE
Clipboard Error

### ISSUE THREAD

**Issue by seanmorley15** [seanmorley15/AdventureLog#236]
Using latest version of Firefox, when trying to add adventure using the public toggle:

` SyntaxError: Unexpected token < in JSON at position 1

at JSON.parse (<anonymous>)

at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19)

at successSteps (node:internal/deps/undici/undici:5555:27)

at fullyReadBody (node:internal/deps/undici/undici:1665:9)

at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

at async specConsumeBody (node:internal/deps/undici/undici:5564:7)

at async create (file:///app/build/server/chunks/4-BXUMQ2IB.js:186:18)

at async handle_action_json_request (file:///app/build/server/index.js:869:18)

at async resolve2 (file:///app/build/server/index.js:3583:24)

at async themeHook (file:///app/build/server/chunks/hooks.server-CKk8-UlX.js:124:10)
[]`

![358859638-cae33946-876f-4f72-9659-c04811dc2657](https://github.com/user-attachments/assets/e24a220e-2b8d-48e0-a5ec-ff22d89e6f5f)

**Comment by seanmorley15** [comment]
This is not actually an AdventureLog bug, using the clipboard API requires a secure origin
![image](https://github.com/user-attachments/assets/3d78ed86-ed71-4b1d-ac12-23729e52d486)

I will make sure that clipboard copying is stopped if not secure to prevent these messages

**Comment by seanmorley15** [comment]
This has been resolved in #240
